# Generated by Django 3.0.6 on 2020-06-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0002_auto_20200616_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
